# Text Generation

In [1]:
# TEXT generation using gpt 2 from hugging face lib
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")  # the task you want to do and the model

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:122: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [2]:
prompt="what is deep learning"
output=pipe(prompt)

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

In [3]:
print(output[0]["generated_text"])

what is deep learning? I have a theory.

I have a theory. I think there are two main ways to learn deep learning. One is to learn the first approach, which is thinking about the first approach, and learning the second approach, which is thinking about the second approach.

The first approach is to learn the first approach, and the second approach is to think about the second approach.

The way the first approach works, it's like how you learn the first approach, and then you learn the second approach. I think that's very similar to the first approach.

The first approach is like how you learn the first approach, and the second approach is to think about the second approach.

And then you learn the third approach, which is to think about the third approach, and then you learn the fourth approach, which is to think about the fourth approach.

The way the second approach works is that you learn the first approach, and then you learn the second approach, and then you learn the third approach, which is to think about the third approach.

So the third approach is like where you learn the first approach, and then you learn the second approach, and then you learn the third approach, which is to think about

### Loading the model directly

In [4]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [5]:
tokenizer

GPT2Tokenizer(name_or_path='openai-community/gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})

In [6]:
#architecture of gpt2
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [7]:
from transformers import AutoTokenizer
tokenizer=AutoTokenizer.from_pretrained("gpt2")

In [8]:
sentence="step-by-step"
input_ids=tokenizer(sentence) #this will return a dictionary
#converting into tensors
input_ids=tokenizer(sentence,return_tensors="pt")
input_ids=input_ids['input_ids']

In [9]:
tokenizer.decode(input_ids[0])

'step-by-step'

In [10]:
sentence="unbelivable"
input_ids=tokenizer(sentence,return_tensors="pt").input_ids
input_ids

tensor([[  403,  6667, 21911]])

In [11]:
for token_id in input_ids[0]:
  print(tokenizer.decode(token_id))

un
bel
ivable

In [12]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
my_ids = tokenizer(word, return_tensors="pt").input_ids
len(my_ids[0])

15

In [13]:
for token_id in my_ids.squeeze():
  print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis

### Generate using gpt2

In [14]:
from transformers import AutoModelForCausalLM
import torch
import torch.nn.functional as F

In [15]:
gpt2=AutoModelForCausalLM.from_pretrained("gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [16]:
sentence=" I learn machine learning to enhance the performance"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

# print(gpt2(token_ids).logits.shape)
outputs=gpt2(token_ids).logits[0, -1]
tokenizer.decode(outputs.argmax())

' of'

In [17]:
sentence=" I learn machine learning to enhance the"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0, -1]
final_logits=torch.topk(outputs,7)
print(final_logits)

for index in final_logits.indices:
  print(tokenizer.decode(index))

torch.return_types.topk(
values=tensor([-110.0572, -110.1733, -110.5066, -110.7839, -110.9877, -111.2124,
        -111.2452], grad_fn=<TopkBackward0>),
indices=tensor([2854, 2836, 1692, 2694, 4673, 1998, 9332]))
 performance
 user
 human
 ability
 learning
 experience
 efficiency

In [18]:
sentence="I learn machine learning to enhance"

token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0,-1]
tokenizer.decode(outputs.argmax())

' our'

### Sampling Techniques

In [19]:
print(gpt2(token_ids).logits.shape)

torch.Size([1, 6, 50257])

In [20]:
def greedy_decode(logits):
  """Return token index with maximum probablity"""
  return torch.argmax(logits,dim=-1) # dim =-1 because argmax() operate on the last dimension vocab


#TOP K SAMPLING

def top_k_sampling(logits,k=30):
  """keeps only top k logits,normalize them into probablity.
  then sample one token fro the filtered distribution"""

  #unpacking

  values,indices=torch.topk(logits,k)
  #torch.topk returns -> values: the top k highest logits, indices: their positions (token IDs)

  probs=F.softmax(values,dim=-1)
  sampled=torch.multinomial(probs,1)
  return indices[sampled]


# TOP-p SAMPLING

def top_p_sampling(logits,p=0.9):

  """sort the tokens by probablity keep smallest number whose  cumulative probablity exceeds threshold p,
    then sample one token"""
  sorted_logits,sorted_indices=torch.sort(logits,descending=True)
  sorted_probs=F.softmax(sorted_logits,dim=-1)
  cumulative_probs=sorted_probs.cumsum(dim=-1)

  #Mask token outside the threshold
  mask=cumulative_probs>p
  sorted_logits[mask]=float("-inf")

  #Sample rom filtered logits

  filtered_probs = F.softmax(sorted_logits,dim=-1)
  sampled=torch.multinomial(filtered_probs,1)

  # Return token index in originial vocabulary
  return sorted_indices[sampled]


#TEMPERATURE SAMPLING

"""
    Scale logits by temperature before sampling.
    Lower temperature => sharper distribution
"""

def temperature_sampling(logits, temperature=1.0):
  scaled= logits/temperature
  probs=F.softmax(scaled,dim=-1)
  return torch.multinomial(probs,1)


#RANDOM SAMPLING

def random_sampling(logits):
    """
    Sample dirctly from softmax distribution without filtring
    """

    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, 1)

In [21]:
sentence = "I am really happy becuase I have gone back in time.I"
inputs = tokenizer(sentence, return_tensors="pt")
output = gpt2(**inputs)
logits = output.logits[0, -1]

#outputs of different sampling strategies
print(f"Greedy Decode: ", tokenizer.decode([greedy_decode(logits)]))
print(f"Top-K Sampling: ", tokenizer.decode(top_k_sampling(logits, k=10)))
print(f"Top-P-Sampling: ", tokenizer.decode(top_p_sampling(logits, p=0.9)))
print(f"Temp: ", tokenizer.decode(temperature_sampling(logits, temperature=1)))
print(f"Random: ", tokenizer.decode(random_sampling(logits)))

Greedy Decode:   am
Top-K Sampling:   was
Top-P-Sampling:   left
Temp:   would
Random:   had

### **visualizing** the confidence for every token

In [22]:
sentence="i learn machine learning to enhance"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

outputs=gpt2(token_ids).logits #Raw unnormalized outputs
#outputs[0,-1] # last token
outputs=torch.softmax(outputs[0,-1],dim=-1)

top10=torch.topk(outputs,k=10)

for index,value in zip(top10.indices,top10.values):
  print(f"{tokenizer.decode(index)} -- {value:.1}")

 the -- 0.1
 your -- 0.08
 their -- 0.06
 our -- 0.06
 its -- 0.06
 his -- 0.04
 human -- 0.02
 my -- 0.02
 her -- 0.01
 a -- 0.01

# Sentiment Analysis

In [23]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

In [24]:
type(ds)

datasets.dataset_dict.DatasetDict

In [25]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [26]:
ds["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [27]:
import pandas as pd
ds["train"].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [28]:
my_dataset_df=ds["train"].to_pandas()

In [29]:
my_dataset_df["text"]

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [30]:
len(my_dataset_df["text"])

25000

### Loading model Distilbert, Finbert

In [31]:
from transformers import pipeline
classifier=pipeline("sentiment-analysis",model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [32]:
classifier("this day is great")

[{'label': 'POSITIVE', 'score': 0.9998873472213745}]

In [33]:
#fetching the labels only
result=classifier("this day is worst,nothing is going my way")[0]
print(result["label"])

NEGATIVE

In [34]:
finbert=pipeline("sentiment-analysis",model="ProsusAI/finbert")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [35]:
sentence="the company reported a stron increase increase in quarterly revenue,exceeding market expectations"
finbert(sentence)

[{'label': 'positive', 'score': 0.9531447887420654}]

In [36]:
sentences = ["Strong consumer demand drove record sales across all regions",
"Supply chain disruptions severly affected production output"]

finbert(sentences)

[{'label': 'positive', 'score': 0.9434744715690613},
 {'label': 'negative', 'score': 0.9608097672462463}]